server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.60:8848 #配置Nacos集群地址

management:
  endpoints:
    web:
      exposure:
        include: '*'