server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com    #eureka服务端的实例名字
  client:
    register-with-eureka: false #表识不向注册中心注册自己
    fetch-registry: false #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    #关闭eureka的自我保护机制
    enable-self-preservation: false
    #服务在2秒钟还没心跳反应，立刻就从eureka中删除
    eviction-interval-timer-in-ms: 2000